// <auto-generated />
using System;
using CotdQualifierRankWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CotdQualifierRankWeb.Migrations
{
    [DbContext(typeof(CotdContext))]
    partial class CotdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("CotdQualifierRankWeb.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("NadeoChallengeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NadeoCompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NadeoMapUid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competition", (string)null);
                });

            modelBuilder.Entity("CotdQualifierRankWeb.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Record", (string)null);
                });

            modelBuilder.Entity("CotdQualifierRankWeb.Models.Record", b =>
                {
                    b.HasOne("CotdQualifierRankWeb.Models.Competition", null)
                        .WithMany("Leaderboard")
                        .HasForeignKey("CompetitionId");
                });

            modelBuilder.Entity("CotdQualifierRankWeb.Models.Competition", b =>
                {
                    b.Navigation("Leaderboard");
                });
#pragma warning restore 612, 618
        }
    }
}
